/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'audio-files': AudioFile;
    audio: Audio;
    achievements: Achievement;
    events: Event;
    'member-categories': MemberCategory;
    'member-photo': MemberPhoto;
    'member-roles': MemberRole;
    members: Member;
    gallery: Gallery;
    forms: Form;
    'form-submissions': FormSubmission;
    resources: Resource;
    simulators: Simulator;
    tags: Tag;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audio-files': AudioFilesSelect<false> | AudioFilesSelect<true>;
    audio: AudioSelect<false> | AudioSelect<true>;
    achievements: AchievementsSelect<false> | AchievementsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'member-categories': MemberCategoriesSelect<false> | MemberCategoriesSelect<true>;
    'member-photo': MemberPhotoSelect<false> | MemberPhotoSelect<true>;
    'member-roles': MemberRolesSelect<false> | MemberRolesSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    simulators: SimulatorsSelect<false> | SimulatorsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'about-page': AboutPage;
    'feedback-page': FeedbackPage;
  };
  globalsSelect: {
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'feedback-page': FeedbackPageSelect<false> | FeedbackPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Upload audio assets used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-files".
 */
export interface AudioFile {
  id: number;
  /**
   * Friendly name to identify this audio file in pickers.
   */
  title: string;
  /**
   * Optional tags to group or search audio files.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Configure how each sound behaves on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio".
 */
export interface Audio {
  id: number;
  /**
   * Friendly name shown in the admin list.
   */
  name: string;
  /**
   * Controls where this sound is used in the frontend.
   */
  type: 'buttonClick' | 'mouseClick' | 'pageChange' | 'scroll' | 'background' | 'custom';
  enabled?: boolean | null;
  /**
   * Base volume for this sound.
   */
  volume: number;
  loop?: boolean | null;
  /**
   * 1 = normal speed. Lower is slower, higher is faster.
   */
  playbackRate?: number | null;
  fadeInMs?: number | null;
  fadeOutMs?: number | null;
  /**
   * Optional boost multiplier applied by the frontend.
   */
  volumeBoost?: number | null;
  effects?: {
    echo?: {
      enabled?: boolean | null;
      delayMs?: number | null;
      feedback?: number | null;
      mix?: number | null;
    };
    ambience?: {
      enabled?: boolean | null;
      mix?: number | null;
      lowpassHz?: number | null;
    };
  };
  /**
   * Add one or more sources. The frontend can pick randomly.
   */
  sources?:
    | {
        label?: string | null;
        file?: (number | null) | AudioFile;
        /**
         * Use this for hosted audio (e.g., CDN).
         */
        externalUrl?: string | null;
        /**
         * Higher weight makes this source more likely to be chosen.
         */
        weight?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: number;
  title: string;
  summary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Date of the achievement (newest first)
   */
  date: string;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * E.g., "Workshop", "Seminar", "Social Event"
   */
  category: string;
  title: string;
  /**
   * URL-friendly version (auto-generated from title, but you can edit it)
   */
  slug: string;
  /**
   * When the event happens. Controls ordering and the automatic NEW badge.
   */
  eventDate: string;
  /**
   * Online events hide the venue/map tabs and show a meeting link
   */
  eventMode: 'inPerson' | 'online';
  /**
   * Google Meet / Zoom / stream URL shown for online events
   */
  meetingLink?: string | null;
  /**
   * Optional — when set, the event shows a Register button linking to this form
   */
  registrationForm?: (number | null) | Form;
  /**
   * Main image shown in carousel and modal
   */
  image: number | Media;
  /**
   * Brief tagline shown on the carousel card (optional)
   */
  shortDescription?: string | null;
  /**
   * Full details about the event (shown in modal popup)
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  venue?: {
    roomName?: string | null;
    floor?: string | null;
  };
  contact?: {
    /**
     * Email for questions about this event
     */
    email?: string | null;
    /**
     * Phone number for event inquiries
     */
    phone?: string | null;
  };
  location?: {
    /**
     * Full street address (e.g., "123 Main St, City, Country")
     */
    address?: string | null;
    /**
     * Click on the map to pin the exact event location
     */
    coords?: {
      lat?: number | null;
      lng?: number | null;
    };
    /**
     * Zoom level for the embedded map (1=world view, 18=street level)
     */
    zoom?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Forms shown on the website. Answers are saved here and forwarded to the linked Google Form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  slug: string;
  type: 'registration' | 'feedback' | 'general';
  /**
   * Inactive forms show a closed message instead of the form
   */
  active?: boolean | null;
  /**
   * Optional — the form closes automatically after this time
   */
  deadline?: string | null;
  /**
   * Shown under the form title
   */
  description?: string | null;
  /**
   * The Google Form link (viewform URL). Submissions are forwarded to it so responses appear in the linked Sheet.
   */
  googleFormUrl: string;
  /**
   * Each step is one screen of the wizard
   */
  steps: {
    stepTitle: string;
    stepDescription?: string | null;
    fields: {
      label: string;
      fieldType: 'text' | 'email' | 'phone' | 'number' | 'textarea' | 'select' | 'radio' | 'checkbox' | 'date';
      required?: boolean | null;
      /**
       * Half-width fields pair up side by side on desktop
       */
      width?: ('full' | 'half') | null;
      placeholder?: string | null;
      /**
       * Choices — must match the Google Form options exactly
       */
      options?:
        | {
            option: string;
            id?: string | null;
          }[]
        | null;
      /**
       * From the Google Form pre-filled link, e.g. entry.123456789 (digits alone also work)
       */
      googleEntryId: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  confirmationMessage?: string | null;
  /**
   * Offer a certificate download after submitting (feedback forms)
   */
  showCertificate?: boolean | null;
  /**
   * Background image/PDF for the generated certificate
   */
  certificateTemplate?: (number | null) | Media;
  certificateConfig?: {
    nameX?: number | null;
    nameY?: number | null;
    fontSize?: number | null;
    color?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-categories".
 */
export interface MemberCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Order in which this category appears. Lower numbers appear first. Picking an occupied position swaps with (or shifts) the other category automatically.
   */
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-photo".
 */
export interface MemberPhoto {
  id: number;
  /**
   * e.g., "Photo of John Doe"
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    profile?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-roles".
 */
export interface MemberRole {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Order in which this role appears. Lower numbers appear first. Picking an occupied position swaps with (or shifts) the other role automatically.
   */
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  fullName: string;
  photo: number | MemberPhoto;
  category: number | MemberCategory;
  /**
   * A member can hold multiple roles over time (e.g. Member, then President). First role listed is shown most prominently.
   */
  roles: (number | MemberRole)[];
  bio?: string | null;
  /**
   * e.g. 2021
   */
  startYear: number;
  /**
   * Leave empty if still active
   */
  endYear?: number | null;
  github?: string | null;
  linkedin?: string | null;
  socialAccounts?:
    | {
        platform?: ('twitter' | 'instagram' | 'facebook' | 'youtube' | 'tiktok' | 'other') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Add images and give each one a caption. They render as a masonry wall.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  /**
   * Drag to reorder. Pick each image from Media (or drag new files in).
   */
  photos: {
    image: number | Media;
    /**
     * What is this photo? Shown on hover.
     */
    caption?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Read-only log of website form submissions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  /**
   * Label → answer map exactly as submitted
   */
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Whether the answers reached the Google Form / Sheet
   */
  googleForwardStatus: 'forwarded' | 'failed' | 'pending';
  updatedAt: string;
  createdAt: string;
}
/**
 * Technical learning resources with flexible content blocks
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  /**
   * URL-friendly version (auto-generated from title, but you can edit it)
   */
  slug: string;
  /**
   * One-line summary shown in resource cards and previews
   */
  description: string;
  /**
   * Image displayed in resource cards (1-2 sentence preview)
   */
  thumbnail: number | Media;
  /**
   * Difficulty level for this resource
   */
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  /**
   * Categorize this resource with tags (Python, React, Backend, etc.)
   */
  tags?: (number | Tag)[] | null;
  /**
   * Approximate time to complete this resource
   */
  estimatedReadTime?: number | null;
  /**
   * Feature this resource on the homepage
   */
  featured?: boolean | null;
  /**
   * Tutorials appear on the Tutorials page, resources on Resources
   */
  type: 'resource' | 'tutorial';
  /**
   * Optional label shown on the card. "New" is added automatically for the first 14 days
   */
  badge?: ('featured' | 'popular' | 'essential') | null;
  /**
   * When this resource was last updated
   */
  lastUpdated?: string | null;
  /**
   * Build your resource with flexible content blocks. Add text, code, tables, images, diagrams, and more.
   */
  content?: (TextBlock | CodeBlock | TableBlock | GraphBlock | ImageBlock | RowBlock | SimulatorLinkBlock)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Resource tags for categorization and filtering
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * URL-friendly version (auto-generated from name, but you can edit it)
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  /**
   * Formatted text content with support for bold, italic, lists, and more
   */
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'textBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  /**
   * Programming language for syntax highlighting
   */
  language:
    | 'javascript'
    | 'typescript'
    | 'python'
    | 'java'
    | 'cpp'
    | 'csharp'
    | 'go'
    | 'rust'
    | 'ruby'
    | 'php'
    | 'swift'
    | 'kotlin'
    | 'html'
    | 'css'
    | 'sql'
    | 'bash'
    | 'yaml'
    | 'json'
    | 'markdown'
    | 'xml';
  /**
   * Paste or write your code here
   */
  code: string;
  /**
   * Optional caption or file name to display above the code
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'codeBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableBlock".
 */
export interface TableBlock {
  /**
   * Column headers for the table
   */
  headers: {
    header: string;
    id?: string | null;
  }[];
  /**
   * Table rows and cells
   */
  rows: {
    cells: {
      cell: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'tableBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GraphBlock".
 */
export interface GraphBlock {
  /**
   * Type of graph or diagram to display
   */
  graphType: 'mermaid' | 'chartData' | 'html';
  /**
   * Mermaid diagram syntax (e.g., graph TD, flowchart, etc.)
   */
  mermaidDefinition?: string | null;
  /**
   * Chart data in JSON format (Chart.js compatible)
   */
  chartData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Custom HTML for embedding (use with caution)
   */
  html?: string | null;
  /**
   * Optional caption for the diagram
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'graphBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  /**
   * Upload an image to display
   */
  image: number | Media;
  /**
   * Optional caption or alt text for the image
   */
  caption?: string | null;
  /**
   * Display width of the image
   */
  size?: ('small' | 'medium' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RowBlock".
 */
export interface RowBlock {
  /**
   * Number of columns in this row
   */
  columns: '1' | '2' | '3';
  /**
   * Blocks to display in this row (nested RowBlocks not supported)
   */
  blocks?: (TextBlock | CodeBlock | TableBlock | GraphBlock | ImageBlock | SimulatorLinkBlock)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rowBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SimulatorLinkBlock".
 */
export interface SimulatorLinkBlock {
  /**
   * Select the simulator to link to
   */
  simulator: number | Simulator;
  /**
   * Text to display on the action button
   */
  buttonText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'simulatorLinkBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulators".
 */
export interface Simulator {
  id: number;
  title: string;
  slug: string;
  description: string;
  thumbnail: number | Media;
  category: 'microcontrollers' | 'protocols' | 'rtos' | 'peripherals' | 'architecture';
  tags?: (number | Tag)[] | null;
  difficulty?: ('beginner' | 'intermediate' | 'advanced') | null;
  /**
   * Estimated time to complete in minutes
   */
  estimatedTime?: number | null;
  content?: (TextBlock | CodeBlock | TableBlock | GraphBlock | ImageBlock | RowBlock | SimulatorLinkBlock)[] | null;
  /**
   * URL of the interactive simulator iframe
   */
  iframeUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audio-files';
        value: number | AudioFile;
      } | null)
    | ({
        relationTo: 'audio';
        value: number | Audio;
      } | null)
    | ({
        relationTo: 'achievements';
        value: number | Achievement;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'member-categories';
        value: number | MemberCategory;
      } | null)
    | ({
        relationTo: 'member-photo';
        value: number | MemberPhoto;
      } | null)
    | ({
        relationTo: 'member-roles';
        value: number | MemberRole;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'simulators';
        value: number | Simulator;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-files_select".
 */
export interface AudioFilesSelect<T extends boolean = true> {
  title?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio_select".
 */
export interface AudioSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  enabled?: T;
  volume?: T;
  loop?: T;
  playbackRate?: T;
  fadeInMs?: T;
  fadeOutMs?: T;
  volumeBoost?: T;
  effects?:
    | T
    | {
        echo?:
          | T
          | {
              enabled?: T;
              delayMs?: T;
              feedback?: T;
              mix?: T;
            };
        ambience?:
          | T
          | {
              enabled?: T;
              mix?: T;
              lowpassHz?: T;
            };
      };
  sources?:
    | T
    | {
        label?: T;
        file?: T;
        externalUrl?: T;
        weight?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  date?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  category?: T;
  title?: T;
  slug?: T;
  eventDate?: T;
  eventMode?: T;
  meetingLink?: T;
  registrationForm?: T;
  image?: T;
  shortDescription?: T;
  description?: T;
  venue?:
    | T
    | {
        roomName?: T;
        floor?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  location?:
    | T
    | {
        address?: T;
        coords?:
          | T
          | {
              lat?: T;
              lng?: T;
            };
        zoom?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-categories_select".
 */
export interface MemberCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-photo_select".
 */
export interface MemberPhotoSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        profile?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-roles_select".
 */
export interface MemberRolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  fullName?: T;
  photo?: T;
  category?: T;
  roles?: T;
  bio?: T;
  startYear?: T;
  endYear?: T;
  github?: T;
  linkedin?: T;
  socialAccounts?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  active?: T;
  deadline?: T;
  description?: T;
  googleFormUrl?: T;
  steps?:
    | T
    | {
        stepTitle?: T;
        stepDescription?: T;
        fields?:
          | T
          | {
              label?: T;
              fieldType?: T;
              required?: T;
              width?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    option?: T;
                    id?: T;
                  };
              googleEntryId?: T;
              id?: T;
            };
        id?: T;
      };
  confirmationMessage?: T;
  showCertificate?: T;
  certificateTemplate?: T;
  certificateConfig?:
    | T
    | {
        nameX?: T;
        nameY?: T;
        fontSize?: T;
        color?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  answers?: T;
  googleForwardStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  thumbnail?: T;
  difficulty?: T;
  tags?: T;
  estimatedReadTime?: T;
  featured?: T;
  type?: T;
  badge?: T;
  lastUpdated?: T;
  content?:
    | T
    | {
        textBlock?: T | TextBlockSelect<T>;
        codeBlock?: T | CodeBlockSelect<T>;
        tableBlock?: T | TableBlockSelect<T>;
        graphBlock?: T | GraphBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        rowBlock?: T | RowBlockSelect<T>;
        simulatorLinkBlock?: T | SimulatorLinkBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock_select".
 */
export interface CodeBlockSelect<T extends boolean = true> {
  language?: T;
  code?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableBlock_select".
 */
export interface TableBlockSelect<T extends boolean = true> {
  headers?:
    | T
    | {
        header?: T;
        id?: T;
      };
  rows?:
    | T
    | {
        cells?:
          | T
          | {
              cell?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GraphBlock_select".
 */
export interface GraphBlockSelect<T extends boolean = true> {
  graphType?: T;
  mermaidDefinition?: T;
  chartData?: T;
  html?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RowBlock_select".
 */
export interface RowBlockSelect<T extends boolean = true> {
  columns?: T;
  blocks?:
    | T
    | {
        textBlock?: T | TextBlockSelect<T>;
        codeBlock?: T | CodeBlockSelect<T>;
        tableBlock?: T | TableBlockSelect<T>;
        graphBlock?: T | GraphBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        simulatorLinkBlock?: T | SimulatorLinkBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SimulatorLinkBlock_select".
 */
export interface SimulatorLinkBlockSelect<T extends boolean = true> {
  simulator?: T;
  buttonText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulators_select".
 */
export interface SimulatorsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  thumbnail?: T;
  category?: T;
  tags?: T;
  difficulty?: T;
  estimatedTime?: T;
  content?:
    | T
    | {
        textBlock?: T | TextBlockSelect<T>;
        codeBlock?: T | CodeBlockSelect<T>;
        tableBlock?: T | TableBlockSelect<T>;
        graphBlock?: T | GraphBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        rowBlock?: T | RowBlockSelect<T>;
        simulatorLinkBlock?: T | SimulatorLinkBlockSelect<T>;
      };
  iframeUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  title: string;
  /**
   * Intro text shown at the top of the page (rendered before the sections below).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Richer building blocks rendered below the intro: banner headings, positioned images, and text sections. Reorder freely.
   */
  sections?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            /**
             * Optional image behind the heading
             */
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bannerBlock';
          }
        | {
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutTextBlock';
          }
        | {
            image: number | Media;
            caption?: string | null;
            position?: ('center' | 'left' | 'right') | null;
            size?: ('small' | 'medium' | 'large') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutImageBlock';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-page".
 */
export interface FeedbackPage {
  id: number;
  title: string;
  /**
   * Optional intro shown above the list of feedback forms. The list itself comes from the Feedback Forms collection.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  sections?:
    | T
    | {
        bannerBlock?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        aboutTextBlock?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        aboutImageBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              position?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback-page_select".
 */
export interface FeedbackPageSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'users'
      | 'media'
      | 'audio-files'
      | 'audio'
      | 'achievements'
      | 'events'
      | 'member-categories'
      | 'member-photo'
      | 'member-roles'
      | 'members'
      | 'gallery'
      | 'forms'
      | 'form-submissions'
      | 'resources'
      | 'simulators'
      | 'tags'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}